---
- hosts: localhost
  connection: local
  vars:
    config_template_src_folder: "./config_template_files/"
    json_override:
      "volume:create": ""
      "volume:delete": ""
    ini_override:
      global:
        blabla: car
    yaml_override:
      listb:
        - c
        - e
      listc:
        - newlist
    internal_lb_vip_address: 127.0.0.2
  tasks:
  - name: config_template src no override
    config_template:
      src: "{{ config_template_src_folder }}example.yaml"
      dest: "./tmp/templated-src"
      config_type: yaml
      config_overrides: {}
  - name: config_template content no override
    config_template:
      content: "{{ lookup('file',config_template_src_folder + 'example.yaml',wantlist=True) | join('\n') }}"
      dest: "./tmp/templated-content"
      config_type: yaml
      config_overrides: {}
  - name: diff to see yaml src/content difference
    command: diff ./tmp/templated-content ./tmp/templated-src
    failed_when: false

  - name: config_template src override
    config_template:
      src: "{{ config_template_src_folder }}example.yaml"
      dest: "./tmp/templated-src-override"
      config_type: yaml
      config_overrides: "{{ yaml_override }}"
  - name: config_template content override
    config_template:
      content: "{{ lookup('file',config_template_src_folder + 'example.yaml',wantlist=True) | join('\n') }}"
      dest: "./tmp/templated-content-override"
      config_type: yaml
      config_overrides: "{{ yaml_override }}"
  - name: diff to see yaml src/content difference with overrides
    command: diff ./tmp/templated-content-override ./tmp/templated-src-override
    failed_when: false

  - name: config_template file override
    config_template:
      src: "{{ config_template_src_folder }}example.ini"
      dest: "./tmp/templated-src-ini-override"
      config_type: ini
      config_overrides: "{{ ini_override }}"
  - name: config_template content override lookup file
    config_template:
      content: "{{ lookup('file',config_template_src_folder + 'example.ini',wantlist=True) | join('\n') }}"
      dest: "./tmp/templated-content-ini-override-lookupfile"
      config_type: ini
      config_overrides: "{{ ini_override }}"
  - name: diff to see ini src/content difference with ini overrides
    command: diff ./tmp/templated-content-ini-override-lookupfile ./tmp/templated-src-ini-override
    failed_when: false

  - name: config_template content override lookupurl
    config_template:
      content: "{{ lookup('url','https://raw.githubusercontent.com/openstack/openstack-ansible-os_neutron/master/templates/felix.cfg.j2',wantlist=True) | join('\n') }}"
      dest: "./tmp/templated-content-ini-override-lookupurl"
      config_type: ini
      config_overrides: "{{ ini_override }}"
  - name: diff to see ini content file/url difference
    command: diff ./tmp/templated-content-ini-override-lookupurl ./tmp/templated-content-ini-override-lookupfile
    failed_when: false

  - name: config_template src json
    config_template:
      src: "{{ config_template_src_folder }}/example.json"
      dest: "./tmp/template-src-json"
      config_type: json
      config_overrides: {}
  - name: config_template content json
    config_template:
      content: "{{ lookup('file',config_template_src_folder + 'example.json',wantlist=True) | join('\n') | indent(2,true) }}"
      dest: "./tmp/template-content-json"
      config_type: json
      config_overrides: {}
  - name: diff to see json src/content difference without overrides
    command: diff ./tmp/template-src-json ./tmp/template-content-json
    failed_when: false

  - name: config_template src override json
    config_template:
      src: "{{ config_template_src_folder }}/example.json"
      dest: "./tmp/template-src-json"
      config_type: json
      config_overrides: "{{ json_override }}"
  - name: config_template content override json lookup file
    config_template:
      content: "{{ lookup('file',config_template_src_folder + 'example.json',wantlist=True) | join('\n') | indent(2,true) }}"
      dest: "./tmp/template-content-json"
      config_type: json
      config_overrides: "{{ json_override }}"
  - name: diff to see json src/content difference with overrides
    command: diff ./tmp/template-content-json ./tmp/template-src-json
    failed_when: false

  - name: config_template content override json lookup url
    config_template:
      content: "{{ lookup('url','https://raw.githubusercontent.com/openstack/openstack-ansible-os_cinder/master/templates/policy.json.j2',wantlist=True) | join('\n') | indent(2,true) }}"
      dest: "./tmp/templated-content-json-override-lookupurl"
      config_type: json
      config_overrides: "{{ json_override }}"
  - name: diff to see json content file/url difference
    command: diff ./tmp/templated-content-json-override-lookupurl ./tmp/template-content-json
    failed_when: false
