---
- hosts: localhost
  connection: local
  vars:
    ranthistask: False
  tasks:
    - stat:
        file: "do-not-repeat-the-same-when-for-registered-tasks.yml"
      register: stattask
      when: ranthistask | bool
    - name: test
      debug:
        var: stattask
      when: not stattask | skipped
