---
- hosts: all
  connection: local
  vars_prompt:
    - name: destroy_ok
      prompt: |
        "This action is now destructive and remove items from your
        database. Would you like to continue ? (yes/no)"
      default: no
      private: no
  tasks:
    - name: Set fact to allow distroy
      set_fact:
        destroy: "{{ ( destroy_ok | lower == 'y' or destroy_ok | lower == 'yes') | ternary(True,False) }}"
    - name: debug destroy_ok
      debug:
        var: destroy_ok
    - name: debug destroy
      debug:
        var: destroy

- hosts: localhost
  connection: local
  tasks:
    - name: destroy?
      debug:
        var: destroy
      when: destroy | bool
- hosts: localhost2
  connection: local
  tasks:
    - name: destroy?
      debug:
        var: destroy
      when: destroy | bool
