---
## Method 1
- name: handling service x restart
  debug:
    msg: "handling restart of service x by notifying the service"
  changed_when: True
  notify:
    - restart service x
  tags:
    - method1
    - handling_restart

- name: restart service x
  debug:
    msg: "restarting service x"
  tags:
    - method1
    - service_restart

## Method 2
- name: restart service y
  debug:
    msg: "restarting service y"
  when: >
    ( conditionalhandler_allow_restart | bool or
      conditionalhandler_force_restart | bool )
  tags:
    - method2
    - service_restart

## Method 3
# No handlers needed

## Method 4
- name: marking service a restart
  shell: echo "marking restart of service a" > /tmp/restart_required
  args:
    creates: /tmp/restart_required
  tags:
    - method4
    - handling_restart

- name: restart service a
  debug:
    msg: "restarting service a"
  tags:
    - method4
    - service_restart